### ISSUE TITLE
Python 3.4 compatibility

### ISSUE THREAD

**Issue by lukesg08** [pedal-edu/pedal#14]
Syntax error in assertions.py when dealing with Python 3.4 because of loop unrolling.

**Comment by acbart** [comment]
We no longer support 3.4. In fact, I think it's an open question whether we should support python 3.5. The [Pycharm developer survey](https://www.jetbrains.com/lp/python-developers-survey-2019/) suggests that less than 10% use anything less than 3.6. Considering the massive improvements afforded by 3.6, I think we should stay with that - but be sure to support 3.7, 3.8, 3.9, and whatever comes next.
