### ISSUE TITLE
Deprecate cait.ast_helpers.py

### ISSUE THREAD

**Issue by acbart** [pedal-edu/pedal#48]
Do we still need ast_helpers.py? If it's necessary for dev, but isn't meant to be used by instructors, perhaps it can be moved to some other location like the `tools` main directory?

**Comment by lukesg08** [comment]
Well...It's used when printing CaitNodes and cait_node.py theoretically have a dependence on it (for the __str__ method). One thing that could be done is to remove that dependency and just call the functions in ast_helpers directly when we're attempting to debug something and need to print the CaitNode. But I do think the printing functionality in ast_helpers are better than just printing the object itself. Alternatively, we could integrate the ast_helper functions into the CaitNode class itself.

**Comment by acbart** [comment]
Ah, okay, if it's useful then we can leave it in where it is.
