### ISSUE TITLE
Error running the tutorial

### ISSUE THREAD

**Issue by jrfaller** [pedal-edu/pedal#84]
Hi all, and thanks for this library!

I am trying to follow the tutorial : `pip3 install pedal`

Then, I created a file `grade.py` with

```
# Always start by importing Pedal
from pedal import *

# Load the students' code
student_code = "print('Hello world!')"
contextualize_report(student_code)

# Check their source code for syntax errors
verify()
# Run their code
student = run(student_code)

# ... More instructor logic can go here ...

# Resolve output and print
from pedal.resolvers import print_resolve
print_resolve()
```

And I ran the command `pedal feedback grade.py`.

However, I obtain the following error : 

```
Traceback (most recent call last):
  File "/usr/local/bin/pedal", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pedal/command_line/command_line.py", line 68, in main
    return pipeline(args).execute()
  File "/usr/local/lib/python3.9/site-packages/pedal/command_line/modes.py", line 147, in execute
    self.run_control_scripts()
  File "/usr/local/lib/python3.9/site-packages/pedal/command_line/modes.py", line 291, in run_control_scripts
    bundle.run_ics_bundle(resolver=self.config.resolver,
  File "/usr/local/lib/python3.9/site-packages/pedal/command_line/modes.py", line 104, in run_ics_bundle
    global_data.update(env.setup_environment(self.submission,
TypeError: __init__() got an unexpected keyword argument 'skip_run'
```

Do you know if I have missed something?

Cheers.

**Comment by lukesg08** [comment]
Right now our standard configuration for the command line is bugged. Please use --environment blockpy for now, so the commandline input should look like:
`feedback grade_assignment.py student.py --environment blockpy`

I believe the blockpy environment should have the standard features that people would use (sandboxed running, threaded execution of student code, etc.).

one comment is that you are missing the student submission file in your command line argument run. The tutorial bit that was first was just running it's own independent script just to get a feel for how you might do things in Pedal.

See the examples in https://pedal-edu.github.io/pedal/teachers/examples.html

If you take the first example in the above link (student.py and grade_assignment.py), and run the command line argument as shown above, it should run properly.

**Comment by lukesg08** [comment]
PyPi version should now be updated with this bug fix so specifying

`feedback grade_assignment.py student.py`

without specifying an environment should work properly now.

**Comment by jrfaller** [comment]
Hi @lukesg08 and thanks a lot for this quick answer.

I confirm that the problem I had is now resolved : `pedal feedback grade.py test.py`:

```
442ms
grade.py test.py
Complete
Great work!
```
