### ISSUE TITLE
Pedal's "types.py" collides with the Python library's types module.

### ISSUE THREAD

**Issue by clause** [pedal-edu/pedal#86]
Pedal's "types" module has the same name as Python's built-in "types" module (https://github.com/python/cpython/blob/3.10/Lib/types.py). This causes issues when (e.g,, PyCharm's test runner) expects the system types but encounters Pedal's first.

**Comment by acbart** [comment]
Oh! Good to know. We can fold this into the Type System upgrades this summer, I hope.
